workflows:
  ios-simulator-vicdan:
    name: iOS Simulator Build (Vicdan)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Temizlik Yap (Clean)
        script: flutter clean
      - name: Bagimliliklari Yükle
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;
      - name: Simulator Icin Derle
        script: |
          # Simülatör modunda imzalamadan derle
          flutter build ios --debug --simulator --no-codesign
      - name: Vicdan.zip Olustur
        script: |
          cd build/ios/iphonesimulator
          rm -f Vicdan_Sim.zip
          zip -r Vicdan_Sim.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Vicdan_Sim.zip
