workflows:
  ios-simulator-build:
    name: iOS Simulator Build for Appetize
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS Simulator .app
        script: |
          flutter build ios --debug --simulator
      - name: Zip the .app for Appetize
        script: |
          cd build/ios/iphonesimulator
          zip -r content.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/content.zip
