workflows:
  ios-simulator-nefes:
    name: iOS Simulator Build (Nefes)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Temizlik Yap (Clean)
        script: flutter clean
      - name: Bagimliliklari Yükle
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;
      - name: Simulator Icin Derle
        script: |
          # Simülatör modunda imzalamadan derle
          flutter build ios --debug --simulator --no-codesign
      - name: Nefes.zip Olustur
        script: |
          cd build/ios/iphonesimulator
          rm -f Nefes_Sim.zip
          zip -r Nefes_Sim.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Nefes_Sim.zip
